[package]
name = "star_soldier_extract"
version = "0.1.0"
authors = ["taotao54321 <taotao54321@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
eyre = "0.6"
image = "0.23"
imageproc = "0.22"
itertools = "0.9"
once_cell = "1.5"
rusttype = "0.9"
structopt = "0.3"
