#!/usr/bin/env python3

import subprocess


def go(cmd):
    subprocess.run(cmd.split(), check=True)


def main():
    go("cargo run --release --bin cell_matrix -- StarSoldier.nes CellMatrix-1.png")
    go(
        "cargo run --release --bin cell_matrix -- --second-round StarSoldier.nes CellMatrix-2.png"
    )

    go("cargo run --release --bin meta_sprite_matrix -- StarSoldier.nes MetaSpriteMatrix-1.png")
    go(
        "cargo run --release --bin meta_sprite_matrix -- --second-round StarSoldier.nes MetaSpriteMatrix-2.png"
    )

    for i in range(1, 16 + 1):
        go(f"cargo run --release --bin ground -- StarSoldier.nes {i} Ground-1-{i:02}.png")
        go(
            f"cargo run --release --bin ground -- --second-round StarSoldier.nes {i} Ground-2-{i:02}.png"
        )


if __name__ == "__main__":
    main()
